
alpaca: alpaca.e
 ex alpaca.e -o alpaca -lui -lpkg.1

clean:
 rm alpaca.o alpaca

install: alpaca
 install alpaca /bin
 install alpaca.desktop /res/apps
 install alpaca.png /res/icons
 install installed.png update.png deleted.png /res/alpaca
