navigator: navigator.e
 ex navigator.e -o navigator -lui -lfiletype

clean:
 rm navigator.o navigator

install: navigator
 install navigator ./bin
 install navigator.desktop ./res/apps
 install audio.png up.png lib.png dir.png text.png image.png unknown.png exec.png video.png ./res/navigator/